# Generated by Django 3.1.14 on 2022-08-02 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('C++', 'C++'), ('C', 'C'), ('C#', 'C#'), ('Prolog', 'Prolog'), ('R', 'R'), ('Rust', 'Rust'), ('SQL', 'SQL')], max_length=10)),
                ('text', models.CharField(max_length=2000)),
                ('dificulty', models.IntegerField(default=1)),
                ('attachments', models.ManyToManyField(to='tasks.Attachment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('password', models.TextField(default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(to='tasks.Task')),
            ],
        ),
    ]
